# Generated by Django 5.2.6 on 2026-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('reset_password', 'Reset Password'), ('transfer_confirm', 'Transfer Confirmation')], max_length=20),
        ),
    ]
