# Generated by Django 5.2.6 on 2026-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_back',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_front',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='submitted_for_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_registration',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_docs/'),
        ),
    ]
