# Generated by Django 5.2.6 on 2026-01-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='is_active',
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtual_bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtual_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
